### ISSUE TITLE
distributed optimization with communication

### ISSUE THREAD

**Issue by jeff-regier** [jeff-regier/Celeste.jl#289]
Subtasks:
- [x] Cyclades version of `one_node_infer()`, aka  `one_node_cyclades()` 
- [x] unit tests with synthetic data showing a case where  `one_node_cyclades()` improves on `one_node_infer()` (in terms of  the objective value)
- [ ] Compare runtimes to convergence of `one_node_cyclades()` and `one_node_infer()`, for several cases
- [ ] Compare runtimes and accuracy on real data
- [ ] Compare accuracy on Galsim data
- [ ] #290 -- show serial algorithm (block coordinate ascent w/Newton block updates) converges
- [ ] #384 -- multi-node Cyclades, with just a few nodes
- [ ] Single-thread script that counts connected components in a bounding box
- [ ] #307 -- count SDSS connected components
