### ISSUE TITLE
GB LLVM Optimization tracker

### ISSUE THREAD

**Issue by Keno** [jeff-regier/Celeste.jl#639]
As we approach GB, the majority of the remaining optimizations will happen at the LLVM IR level. I'll keep a list of issues here and update as a go along.

## Working on hotspots
It's useful to try LLVM improvements in isolation. For that, we can split out the objective function like so:
```
JULIA_NUM_THREADS=1 ~/julia/julia --output-bc sys-all.bc --sysimage ~/julia/usr/lib/julia/sys.so --depwarn=no --startup-file=no -O3 --eval 'include("benchmark_one_light_source.jl")'
~/llvm-debug-build/bin/llvm-extract --recursive -rfunc .*elbo_likelihood.* sys-all.bc > hotspot.bc
~/llvm-debug-build/bin/llvm-extract --delete --recursive -rfunc .*elbo_likelihood.* sys-all.bc > residual.bc
~/julia/usr/tools/llc residual.bc -fp-contract=fast -mcpu=haswell -relocation-model=pic -filetype=obj -o residual.o
# Do optimizations on hotspot.bc here
~/julia/usr/tools/llc hotspot.bc -fp-contract=fast -mcpu=haswell -relocation-model=pic -filetype=obj -o hotspot.o
cc -shared -o sys-all.so residual.o hotspot.o -L ~/julia/usr/lib -ljulia
```

# Current build script

```
JULIA_NUM_THREADS=1 ~/julia/julia --output-bc sys-all.bc --sysimage ~/julia/usr/lib/julia/sys.so --depwarn=no --startup-file=no -O3 --eval 'include("../benchmark_one_light_source.jl")'
~/llvm-debug-build/bin/llvm-extract --recursive -rfunc .*elbo_likelihood.* -rfunc .*first_quad_form.* -rfunc .*propagate_derivatives.* sys-all.bc > hotspot.bc
~/llvm-debug-build/bin/llvm-extract --delete --recursive -rfunc .*elbo_likelihood.* -rfunc .*first_quad_form.* -rfunc .*propagate_derivatives.* sys-all.bc > residual.bc
#~/julia/usr/tools/llc residual.bc -fp-contract=fast -mcpu=haswell -relocation-model=pic -filetype=obj -o residual.o
#~/julia/usr/tools/llc hotspot.bc -fp-contract=fast -mcpu=haswell -relocation-model=pic -filetype=obj -o hotspot.o
#cc -shared -o sys-all.so residual.o hotspot.o -L ~/julia/usr/lib -ljulia
~/llvm-debug-build/bin/opt -inline-threshold=3000 -inline hotspot.bc > hotspot-inlined.bc
~/llvm-debug-build/bin/llvm-extract -S -rfunc .*populate_gal_fsm.* hotspot-inlined.bc > gal_fsm.ll
~/llvm-debug-build/bin/opt -strip-debug -memdep-block-scan-limit=10000 -tbaa -basicaa -scev-aa -scoped-noalias -S -mcpu haswell -licm -gvn -dse -instcombine -sroa -instcombine -licm -instcombine -newgvn -licm -instcombine -lcssa -dse gal_fsm.ll > gal_fsm2.ll
# Poor man's LLVM pass - Can be done properly - no time
sed -i 's/fadd/fadd fast/g' gal_fsm2.ll
sed -i 's/fsub/fsub fast/g' gal_fsm2.ll
sed -i 's/fmul/fmul fast/g' gal_fsm2.ll
~/llvm-debug-build/bin/opt -tbaa -basicaa -scev-aa -scoped-noalias -mcpu haswell -vector-library=SVML -loop-vectorize -instcombine -S gal_fsm2.ll > gal_fsm_vectorized.ll
~/llvm-debug-build/bin/llvm-extract --delete -S -rfunc .*populate_gal_fsm.* hotspot.bc > hotspot-rest.bc
~/llvm-debug-build/bin/opt -tbaa -basicaa -scev-aa -scoped-noalias -mcpu haswell -licm -gvn -slp-vectorizer -instcombine -loop-vectorize -instcombine hotspot-rest.bc > hotspot-rest-opt.bc
#~/llvm-debug-build/bin/opt -tbaa -basicaa -scev-aa -scoped-noalias -mcpu haswell -licm -gvn -loop-vectorize -instcombine residual.bc > residual-opt.bc
~/julia/usr/tools/llc residual.bc -fp-contract=fast -mcpu=haswell -relocation-model=pic -filetype=obj -o residual.o
~/julia/usr/tools/llc hotspot-rest-opt.bc -fp-contract=fast -mcpu=haswell -relocation-model=pic -filetype=obj -o hotspot.o
~/julia/usr/tools/llc gal_fsm_vectorized.ll -fp-contract=fast -mcpu=haswell -relocation-model=pic -filetype=obj -o gal_fsm.o
cc -shared -o sys-all.so residual.o hotspot.o gal_fsm.o -L ~/julia/usr/lib -ljulia -lsvml
```

# List of issues

- [x] After IPO fix, combine_hessian pointers don't LICM anymore - solved by putting back tbaa_stack on arguments
- [x] Unoptimized memcpy in transform_bvn_derivs
    - Solved by extra -sroa on hotspots
    - General solution is http://bugs.llvm.org/show_bug.cgi?id=32570
- [x] Unoptimized memset in transform_bvn_derivs
    - Sore-to-Load forwarding partially solved by moving second fast fill down to before it's used - general solution is http://bugs.llvm.org/show_bug.cgi?id=32571
    - Still doesn't eliminate loads.
    - Solved by Rearranging data structure to make aliasing more obvious
- [x] Redundant shuffles in transform_bvn_derivs
    - Solved by running SLP after BB vetorizer
- [x] Insufficient vectorization in transform_bvn_derivs
     - Solved using the loop vectorizer
- [x] exp not vectorized
    - Solved using the loop vectorizer
- [x] Useless GC frame in accum_galaxy_pos!
    - Solved by avoiding union return and more aggressive GC frame deletion in lowering
- [x] Useless memcpy after inlining
    - Should be solvable by introducing a notion of strict aliasing to julia
    - Currently fails to have the desired effect. Requires improvements in LLVM
       - https://reviews.llvm.org/D31954
       - One more patch to put up as soon as I have time
- [x] Forward diff code is not vectorized
